# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('appointment_id', models.IntegerField()),
                ('patient_id', models.IntegerField(null=True)),
                ('status_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('appointment_start_time', models.DateTimeField(null=True)),
                ('appointment_duration', models.IntegerField(null=True)),
                ('session_start_time', models.DateTimeField(null=True)),
                ('session_end_time', models.DateTimeField(null=True)),
                ('check', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-status_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('appointment_id', 'appointment_start_time')]),
        ),
    ]
